# frozen_string_literal: true

source 'https://rubygems.org'

gem 'csv'
gem 'pg'
gem 'puma'
gem 'rackup'
gem 'require_all'
gem 'sidekiq'
gem 'sinatra'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'simplecov', require: false
end
