services:
        postgres:
                image: postgres
                volumes:
                        - './dataset/init.sql:/docker-entrypoint-initdb.d/init.sql'
                environment:
                        POSTGRES_PASSWORD: 123456
                        POSTGRES_USER: admin
                ports:
                        - "5432:5432"
        backend:
                image: ruby
                volumes:
                        - 'Rubygems:/usr/local/bundle'
                        - './ruby:/app'
                working_dir: /app
                ports:
                        - "9292:9292"
                command: bash -c "bundle install && ruby import_from_csv.rb && ruby server.rb puma -o 0.0.0.0 -p 9292"
        frontend:
                image: ruby
                volumes:
                        - 'Rubygems:/usr/local/bundle'
                        - './frontend:/app'
                working_dir: /app
                ports:
                        - "3000:3000"
                command: bash -c "bundle install && ruby server.rb puma -o 0.0.0.0 -p 3000"

volumes:
        Rubygems:



